[config]
schemaVersion = "0.0.1"

[package]
namespace = "MoSadie"
name = "TiltiSlip"
description = "In-game actions from Tiltify donations!"
websiteUrl = "https://github.com/MoSadie/TiltiSlip"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack= "5.4.2100"
MoSadie-MoCore= "2.0.3"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./TiltiSlip/bin/Release/netstandard2.1/com.mosadie.tiltislip.dll"
target = "BepInEx/plugins/MoSadie-TiltiSlip/com.mosadie.tiltislip.dll"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[publish]
repository = "https://thunderstore.io"
communities = [ "slipstream-rogue-space", ]
[publish.categories]
slipstream-rogue-space = [ "mods" ]


